### ISSUE TITLE
Output Not Displayed in Output Frame After Running Code

### ISSUE THREAD

**Issue by mmujtabah** [moe18/DeepMLeet#20]
When executing the provided Python code, the output generated by the code is not displayed in the output frame after clicking the "run" button. This prevents users from seeing the output directly within the platform interface, making it difficult to verify the correctness of the code execution.

**Comment by moe18** [comment]
I get what you mean, but might be difficult to implement using streamlit, planning on redoing the website at some point, but till then I will try and see what I could do.
