### ISSUE TITLE
Add New Section Data Science

### ISSUE THREAD

**Issue by mmujtabah** [moe18/DeepMLeet#8]
Adding this section will be a great idea.

**Comment by moe18** [comment]
What kind of questions would you like to see in a data science section?

**Comment by mmujtabah** [comment]
There are lot of sections which can be added in data science but since it's beginning we can add questions related to data preprocessing, data analysis and data visualization.

We can add more sections in future.

**Comment by moe18** [comment]
Thanks, @mmujtabah, for your suggestions on expanding our content to include key data science concepts. After considering how best to incorporate these topics, I think adding questions related to data preprocessing and data analysis into our existing machine learning section would provide a lot of value and maintain cohesion in our material.

Given the current structure and testing format, integrating data visualization might present some challenges, particularly in designing effective and measurable assessments. For the moment, we'll focus on the areas where we can ensure high-quality, testable content, but I'm definitely open to revisiting the inclusion of data visualization in the future as we evolve. Let's start with these enhancements and keep exploring how we can further develop our offerings.
